apiVersion: v1
kind: ConfigMap
metadata:
  name: nvidia-device-plugin
  namespace: kube-system
  labels:
    app.kubernetes.io/name: nvidia-device-plugin
    app.kubernetes.io/part-of: hybrid-inference
data:
  config.yaml: |
    version: v1
    flags:
      migStrategy: none
      failOnInitError: false
      nvidiaDriverRoot: "/driver-root"
      nvidiaDevRoot: "/"
      plugin:
        passDeviceSpecs: true
        deviceListStrategy:
          - cdi-annotations
        deviceIDStrategy: uuid
        cdiAnnotationPrefix: "cdi.k8s.io/"
        nvidiaCTKPath: "/driver-root/usr/bin/nvidia-ctk"
        containerDriverRoot: "/"
